Header update because there were errors checking out the submodule commit:
git submodule update
error: Server does not allow request for unadvertised object a8df5c24f47b7c84a74011f39e4480360930fe7f
Fetched in submodule path 'header', but it did not contain a8df5c24f47b7c84a74011f39e4480360930fe7f. Direct fetching of that commit failed.